name: shop_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # cupertino styles
  cupertino_icons: ^1.0.2
  #animation
  animated_text_kit: ^4.2.2
  #image
  image_picker: ^0.8.6+1
  #firebase
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10
  cloud_firestore: ^4.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  # flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/images/accessories/
    - assets/images/bags/
    - assets/images/beauty/
    - assets/images/electronics/
    - assets/images/homegarden/
    - assets/images/inapp/
    - assets/images/kids/
    - assets/images/men/
    - assets/images/shoes/
    - assets/images/try/
    - assets/images/women/



  fonts:
    - family: Acme
      fonts:
        - asset: assets/fonts/Acme-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

